### ISSUE TITLE
Implement Grid container to fix works section layout

### ISSUE THREAD

**Issue by jcmnunes** [jcmnunes/mcteixeira#61]
As a user, I want to see all works displayed correctly. This means each work card will have the following properties:

* A minimum width
* A maximum width
* Will go to the next line if there is not enough space

As a developer, I want to use CSS grid, probably using:

```css
.container {
  display: grid;
  grid-gap: 20px;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
}
```
